# Generated by Django 4.2 on 2023-04-23 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='timings',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
