# Generated by Django 4.2 on 2023-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_home', '0002_programs_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('programName', models.CharField(max_length=50)),
            ],
        ),
    ]
